spring:
  profiles:
    active: dev
  application:
    name: demo
  batch:
    job:
      enabled: false # Disable auto-startup of jobs

management:
  endpoints:
    web:
      exposure:
        include: "*"
